from pathlib import Path

path = Path('src/DevBox.App/ViewModels/MainWindowViewModel.cs')
text = path.read_text(encoding='utf-8')
old = '''    private async Task DownloadRuntimeAsync(object? parameter)\n    {\n        if (parameter is not RuntimeRowViewModel runtime || !runtime.CanDownload) return;\n\n        try\n        {\n            await _runtimePlatformService.InstallAsync(runtime.Key, runtime.Version);\n\n            var executableRelativePath = RuntimeExecutable(runtime.Key);\n            var installations = _runtimeManager.GetInstalled(runtime.Key, executableRelativePath);\n            var activated = false;\n            if (!installations.Any(item => item.IsActive))\n            {\n                await _runtimePlatformService.ActivateAsync(runtime.Key, runtime.Version);\n                activated = true;\n            }\n\n            RefreshRuntimes();\n            RefreshStatuses();\n            _dialogs.Info(\n                $\"{runtime.Name} downloaded\",\n                activated\n                    ? $\"{runtime.Name} {runtime.Version} was downloaded, verified and activated.\"\n                    : $\"{runtime.Name} {runtime.Version} was downloaded and verified.\");\n        }\n        catch (Exception ex) when (ex is HttpRequestException or InvalidDataException or IOException or UnauthorizedAccessException or InvalidOperationException or FileNotFoundException)\n        {\n            RefreshRuntimes();\n            RefreshStatuses();\n            _dialogs.Error($\"{runtime.Name} download failed\", ex.Message);\n        }\n    }\n'''
new = '''    private async Task DownloadRuntimeAsync(object? parameter)\n    {\n        if (parameter is not RuntimeRowViewModel runtime || !runtime.CanDownload) return;\n\n        _definitions.TryGetValue(runtime.Key, out var service);\n        var wasRunning = service is not null && _processManager.GetStatus(service).State == ServiceState.Running;\n\n        try\n        {\n            if (wasRunning)\n            {\n                await _processManager.StopAsync(service!);\n            }\n\n            // RuntimeManager.InstallAsync verifies SHA-256 and atomically activates the downloaded version.\n            await _runtimePlatformService.InstallAsync(runtime.Key, runtime.Version);\n\n            if (wasRunning)\n            {\n                await _processManager.StartAsync(service!);\n            }\n\n            RefreshRuntimes();\n            RefreshStatuses();\n            _dialogs.Info(\n                $\"{runtime.Name} downloaded\",\n                $\"{runtime.Name} {runtime.Version} was downloaded, verified and activated.\");\n        }\n        catch (Exception ex) when (ex is HttpRequestException or InvalidDataException or IOException or UnauthorizedAccessException or InvalidOperationException or FileNotFoundException or Win32Exception)\n        {\n            if (wasRunning && service is not null &&\n                _processManager.GetStatus(service).State != ServiceState.Running &&\n                File.Exists(service.ExecutablePath))\n            {\n                try\n                {\n                    await _processManager.StartAsync(service);\n                }\n                catch (Exception recoveryError) when (recoveryError is IOException or UnauthorizedAccessException or InvalidOperationException or FileNotFoundException or Win32Exception)\n                {\n                    _dialogs.Warning(\n                        \"Service recovery failed\",\n                        $\"{runtime.Name} download failed and {service.DisplayName} could not be restarted: {recoveryError.Message}\");\n                }\n            }\n\n            RefreshRuntimes();\n            RefreshStatuses();\n            _dialogs.Error($\"{runtime.Name} download failed\", ex.Message);\n        }\n    }\n'''
count = text.count(old)
if count != 1:
    raise RuntimeError(f'Expected one DownloadRuntimeAsync block, found {count}')
path.write_text(text.replace(old, new, 1), encoding='utf-8', newline='\n')
