using System.Reflection;
using System.Text.Json;
using DevBox.Core.Models;
using DevBox.Core.Services;
using Xunit;

namespace DevBox.Tests;

public sealed class FinalBugSweepRound7Tests
{
    [Fact]
    public void EnvironmentProfile_NullCollectionsAreControlledInvalidData()
    {
        var root = NewRoot();
        try
        {
            File.WriteAllText(Path.Combine(root, "config", "environment-profiles.json"), """
            [{"Key":"broken","DisplayName":"Broken","Kind":"EmptyPhp","Runtimes":null,"Database":null,"Addons":null,"Services":null,"Actions":null}]
            """);
            Assert.Throws<InvalidDataException>(() => new EnvironmentProfileService(root).GetProfiles());
        }
        finally { TryDelete(root); }
    }

    [Fact]
    public void ProjectActions_NullEntryAndArgumentsAreControlledInvalidData()
    {
        var root = NewRoot();
        try
        {
            var sites = new SiteManager(root);
            var workspace = new ProjectWorkspaceService(root, sites, new PhpExtensionInspector(root), new LocalCertificateManager(root));
            _ = workspace.Create(new ProjectCreateRequest("app", "app.test", ProjectKind.EmptyPhp, Https: false, DatabaseEngine: "none", Addons: Array.Empty<string>()));
            var project = Path.Combine(root, "www", "app");
            var service = new ProjectActionService(root, workspace);

            File.WriteAllText(Path.Combine(project, ProjectWorkspaceService.ManifestFileName), """
            {"Name":"app","Domain":"app.test","Kind":"EmptyPhp","Actions":[null]}
            """);
            Assert.Throws<InvalidDataException>(() => service.GetActions(project));

            File.WriteAllText(Path.Combine(project, ProjectWorkspaceService.ManifestFileName), """
            {"Name":"app","Domain":"app.test","Kind":"EmptyPhp","Actions":[{"Key":"bad","DisplayName":"Bad","Executable":"php","Arguments":null}]}
            """);
            Assert.Throws<InvalidDataException>(() => service.GetActions(project));
        }
        finally { TryDelete(root); }
    }

    [Fact]
    public void ManagedServices_RejectNullStateReservedPidPrefixesAndPhpPoolPorts()
    {
        var root = NewRoot();
        try
        {
            var config = Path.Combine(root, "config", "services.json");
            File.WriteAllText(config, "[null]");
            Assert.Throws<InvalidDataException>(() => new ManagedServiceCatalog(root).GetManifests());

            File.Delete(config);
            var catalog = new ManagedServiceCatalog(root);
            var pidCollision = new ManagedServiceManifest(1, "php-pool-8.5.10", "Collision", "runtime/x/tool.exe", [], ".", 15000, "1");
            Assert.Throws<InvalidDataException>(() => catalog.Upsert(pidCollision));

            var dbPidCollision = new ManagedServiceManifest(1, "db-mysql-8.4.11", "Collision", "runtime/x/tool.exe", [], ".", 15001, "1");
            Assert.Throws<InvalidDataException>(() => catalog.Upsert(dbPidCollision));

            var portCollision = new ManagedServiceManifest(1, "custom", "Collision", "runtime/x/tool.exe", [], ".", PhpRuntimePoolManager.GetPort("8.5.10"), "1");
            Assert.Throws<InvalidDataException>(() => catalog.Upsert(portCollision));
        }
        finally { TryDelete(root); }
    }

    [Fact]
    public async Task TaskCenter_ThrowingSubscriberCannotFailTaskExecution()
    {
        var root = NewRoot();
        try
        {
            using var center = new PlatformTaskCenter(root);
            center.TaskChanged += (_, _) => throw new InvalidOperationException("subscriber failure");
            var id = center.Enqueue("fixture", (_, _) => Task.CompletedTask);
            var result = await center.WaitAsync(id);
            Assert.Equal(PlatformTaskState.Completed, result.State);
            Assert.Equal(100, result.Progress);
        }
        finally { TryDelete(root); }
    }

    [Fact]
    public async Task AutoGeneratedExportsAreUniqueWithinSameSecond()
    {
        var root = NewRoot();
        try
        {
            var remote = new RemoteEnvironmentService(root);
            var env1 = remote.ExportProfile("php-minimal");
            var env2 = remote.ExportProfile("php-minimal");
            Assert.NotEqual(env1, env2);
            Assert.True(File.Exists(env1));
            Assert.True(File.Exists(env2));

            var sites = new SiteManager(root);
            var workspace = new ProjectWorkspaceService(root, sites, new PhpExtensionInspector(root), new LocalCertificateManager(root));
            _ = workspace.Create(new ProjectCreateRequest("app", "app.test", ProjectKind.EmptyPhp, Https: false, DatabaseEngine: "none", Addons: Array.Empty<string>()));
            var transfer = new ProjectTransferService(root);
            var first = await transfer.ExportAsync(Path.Combine(root, "www", "app"));
            var second = await transfer.ExportAsync(Path.Combine(root, "www", "app"));
            Assert.NotEqual(first.ArchivePath, second.ArchivePath);
            Assert.True(File.Exists(first.ArchivePath));
            Assert.True(File.Exists(second.ArchivePath));
        }
        finally { TryDelete(root); }
    }

    [Fact]
    public void DatabaseManager_DefaultBackupPathIsUniqueWithinSameSecond()
    {
        var root = NewRoot();
        try
        {
            var manager = new DatabaseManager(root);
            var method = typeof(DatabaseManager).GetMethod("ResolveBackupPath", BindingFlags.Instance | BindingFlags.NonPublic)!;
            var first = (string)method.Invoke(manager, ["app", null])!;
            var second = (string)method.Invoke(manager, ["app", null])!;
            Assert.NotEqual(first, second);
        }
        finally { TryDelete(root); }
    }

    [Fact]
    public void DatabaseRuntimeRegistrations_RejectDuplicateIdentityAndNullEntries()
    {
        var root = NewRoot();
        try
        {
            var path = Path.Combine(root, "config", "database-runtimes.json");
            File.WriteAllText(path, "[null]");
            using (var service = new DatabaseRuntimeService(root))
                Assert.Throws<InvalidDataException>(() => service.GetInstances());

            File.WriteAllText(path, """
            [
              {"Engine":"mysql","Version":"8.4.11","Port":3401},
              {"Engine":"MYSQL","Version":"8.4.11","Port":3402}
            ]
            """);
            using (var service = new DatabaseRuntimeService(root))
                Assert.Throws<InvalidDataException>(() => service.GetInstances());
        }
        finally { TryDelete(root); }
    }

    private static string NewRoot()
    {
        var root = Path.Combine(Path.GetTempPath(), "devbox-final-sweep-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(Path.Combine(root, "config"));
        Directory.CreateDirectory(Path.Combine(root, "www"));
        Directory.CreateDirectory(Path.Combine(root, "tmp"));
        Directory.CreateDirectory(Path.Combine(root, "logs"));
        return root;
    }

    private static void TryDelete(string path)
    {
        try { if (Directory.Exists(path)) Directory.Delete(path, recursive: true); }
        catch (IOException) { }
        catch (UnauthorizedAccessException) { }
    }
}
